### ISSUE TITLE
Create a Solr service

### ISSUE THREAD

**Issue by ellioseven** [ellioseven/de#11]
This can be as simple as adding this to docker-compose.yml:

```
 solr:
    image: solr:6
    ports:
      - "8983"
    volumes:
      - ./lib/solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - drupal
```
