### ISSUE TITLE
Composer global package volume overlays container

### ISSUE THREAD

**Issue by ellioseven** [ellioseven/de#14]
In `services/php/docker-compose.yml`:

```
services:
  php:
    volumes:
      - ./lib/composer:/home/app/.composer
    ...
```

This unfortunately overlays the composer global packages within the PHP image. We loose packages such as presstisimo.

Looking at the `mysql` image, they somehow allow the volume to copy the data volume from the container into the host. How can we do that?
