### ISSUE TITLE
Mount a known_hosts file into de-php

### ISSUE THREAD

**Issue by ellioseven** [ellioseven/de#6]
When connecting to remotes via ssh, the system cannot write to `/home/app/.ssh/known_hosts` as it's read only (upon mounting the private key). An empty known hosts file can be mounted to prevent this issue.

```
services:
  php:
    image: "ellioseven/de-drupal:5.6"
    volumes:
      - ./etc/php/ssh/known_hosts:/home/app/.ssh/known_hosts
```
